/*
 * Grid Logo Showcase v1.3.5
 *
 * Copyright 2013-2021, LambertGroup
 *
 */


 (function(e){function n(a){var b=!1;a=a.substr(a.length-4).toLowerCase();if(".jpg"==a||".png"==a||".gif"==a)b=!0;return b}function p(){var a=-1;"Microsoft Internet Explorer"==navigator.appName&&null!=/MSIE ([0-9]{1,}[.0-9]{0,})/.exec(navigator.userAgent)&&(a=parseFloat(RegExp.$1));return parseInt(a,10)}function k(a,b,f,d,g){a.columns=Math.floor((d-b.margin_left-b.margin_right)/(parseInt(b.columWidth,10)+2*parseInt(b.border,10)+parseInt(b.gutter,10)));1>a.columns&&(a.columns=1);a.columWidth=b.columWidth;
 a.total_images>a.columns&&(a.columWidth=(d-b.margin_left-b.margin_right-2*a.columns*parseInt(b.border,10)-(a.columns-1)*b.gutter)/a.columns);a.columWidth>b.columWidth&&(a.columns++,a.columWidth=(d-b.margin_left-b.margin_right-2*a.columns*parseInt(b.border,10)-(a.columns-1)*b.gutter)/a.columns);for(i=1;i<=a.columns;i++)g=e('<div class="colHolderUnit" rel="'+i+'" id="colHolderUnit_'+i+'"></div>'),f.append(g),g.css({width:a.columWidth+2*parseInt(b.border,10)+"px",height:"auto",display:"block","float":"left",
 "margin-left":1!=i?b.gutter:b.margin_left+"px","margin-top":b.margin_top+"px",background:a.bg_aux,"-webkit-box-sizing":"border-box","-moz-box-sizing":"border-box","-o-box-sizing":"border-box","box-sizing":"border-box"});f.append('<br style="clear:both">')}function l(a,b,f,d){a.colNo=d%a.columns;0===a.colNo&&(a.colNo=a.columns);e("#colHolderUnit_"+a.colNo,f).append(a.currentImg[d]);a.currentImg[d].css({"margin-top":0,"margin-bottom":b.gutter,zoom:"1",width:a.columWidth+"px",height:"auto",display:"block",
 "margin-left":"auto","margin-right":"auto","border-width":b.border+"px","border-color":b.borderColorOFF,"border-style":"solid"});b.showTooltip&&a.currentImg[d].addClass("lbg_grid_tooltip");void 0!=a.currentLink[d]&&""!=a.currentLink[d]&&(f=b.target,void 0!=a.currentTarget[d]&&""!=a.currentTarget[d]&&(f=a.currentTarget[d]),a.currentImg[d].wrap('<a href="'+a.currentLink[d]+'" target="'+f+'"></a>'));b.grayscale&&a.currentImg[d].addClass("lbg_grayscale");a.currentImg[d].on("mouseover",function(){b.grayscale&&
 a.currentImg[d].addClass("disabled");0<b.border&&a.currentImg[d].css({"border-color":b.borderColorON,"border-style":"solid"})});a.currentImg[d].on("mouseout",function(){b.grayscale&&a.currentImg[d].removeClass("disabled");0<b.border&&a.currentImg[d].css({"border-color":b.borderColorOFF,"border-style":"solid"})})}function m(a){a.showTooltip&&e(".lbg_grid_tooltip").tooltip({content:function(){return e(this).attr("title")},position:{my:"center bottom-20",at:"center top",using:function(a,f){e(this).css(a);
 e("<div>").addClass("lbg_grid_arrow").addClass(f.vertical).addClass(f.horizontal).appendTo(this)}}})}e.fn.logogridshowcase=function(a){a=e.extend({},e.fn.logogridshowcase.defaults,a);return this.each(function(){var b=e(this),f=b.parent().width();a.responsiveRelativeToBrowser&&(f=e(window).width());a.origWidth=f;var d=e("<div></div>").addClass("logogridshowcase").addClass(a.type);b.wrap(d);var g=b.parent(".logogridshowcase"),c={total_images:0,columWidth:a.columWidth,columns:1,currentLi:"",currentImg:[],
 currentLink:[],currentTarget:[],colNo:0,bg_aux:a.itemBg,windowWidth:0};n(a.itemBg)&&(c.bg_aux="url("+a.itemBg+")");a.centerPlugin&&g.css({margin:"0 auto"});b=b.find("ul:first");d=b.children();c.total_images=b.children().length;k(c,a,g,f,void 0);c.total_images=0;d.each(function(){c.currentLi=e(this);c.currentLi.is("li")||(c.currentLi=c.currentLi.find("li:first"));c.currentLi.is("li")&&(c.total_images++,c.currentLink[c.total_images]="",c.currentTarget[c.total_images]=a.target,void 0!=c.currentLi.attr("data-link")&&
 ""!=c.currentLi.attr("data-link")&&(c.currentLink[c.total_images]=c.currentLi.attr("data-link"),void 0!=c.currentLi.attr("data-target")&&""!=c.currentLi.attr("data-target")&&(c.currentTarget[c.total_images]=c.currentLi.attr("data-target"))),c.currentImg[c.total_images]=c.currentLi.find("img:first"),l(c,a,g,c.total_images))});m(a);var h=!1;e(window).resize(function(){var b=String(navigator.userAgent).toLowerCase(),d=p();doResizeNow=!0;-1!=d&&9==d&&0==c.windowWidth&&(doResizeNow=!1);c.windowWidth==
 e(window).width()?(doResizeNow=!1,a.windowCurOrientation==window.orientation||-1==b.indexOf("android")&&-1==b.indexOf("ipad")&&-1==b.indexOf("iphone")&&-1==b.indexOf("ipod")&&-1==b.indexOf("webos")||(a.windowCurOrientation=window.orientation,doResizeNow=!0)):c.windowWidth=e(window).width();a.responsive&&doResizeNow&&(!1!==h&&clearTimeout(h),h=setTimeout(function(){var b=a;var d=g.parent().width();b.responsiveRelativeToBrowser&&(d=e(window).width());g.empty();k(c,b,g,d,void 0);c.colNo=0;for(i=1;i<=
 c.total_images;i++)l(c,b,g,i);m(b)},200))})})};e.fn.logogridshowcase.defaults={type:"version1",itemBg:"",columWidth:100,gutter:25,margin_left:25,margin_right:25,margin_top:10,showTooltip:!0,grayscale:!1,responsive:!0,responsiveRelativeToBrowser:!1,centerPlugin:!1,target:"_blank",border:0,borderColorOFF:"transparent",borderColorON:"#FF0000",origWidth:0,origHeight:0,contentHolderUnitOrigWidth:0,contentHolderUnitOrigHeight:0,elementOrigTop:0,origthumbsHolder_MarginTop:0,windowOrientationScreenSize0:0,
 windowOrientationScreenSize90:0,windowOrientationScreenSize_90:0,windowCurOrientation:0}})(jQuery);
